cache:
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

language: python

matrix:
  include:
    - os: linux
      python: 3.8
    - os: linux
      python: 3.7
    - os: osx
      language: generic

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > miniconda.sh;
      export TRAVIS_PYTHON_VERSION="3.6";
    else
      wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - md5sum miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  # Need to install setuptools via conda, otherwise the update tries to uninstall it
  - conda install setuptools
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # We shouldn't need to do this, but we get compile failures otherwise as the 
  # gcc we're looking for is missing.
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then
      conda install -c conda-forge gxx_linux-64;
    fi
  - conda install --yes --file=python/requirements/conda-minimal.txt
  #- conda install -c bioconda --yes pysam
  # codecov requires a more recent version of certifi, but we can't uninstall the old one
  # see https://github.com/tskit-dev/tskit/issues/366
  - pip install --ignore-installed certifi
  - HTSLIB_CONFIGURE_OPTIONS=--disable-bz2 pip install -r python/requirements/development.txt
  - pip install -e python

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      nosetests -vs --processes=`sysctl -n hw.ncpu` --process-timeout=5000 tests;
    else
      nosetests -vs --processes=`nproc` --process-timeout=5000 tests;
    fi

