line-length = 90

[lint]
select = ["E", "F", "B", "W", "I", "N", "UP", "A", "RUF", "PT", "NPY"]
# N803,806,802 Allow capital varnames
# E741 Allow "l" as var name
# PT011 allow pytest raises without match
ignore = ["N803", "N806", "N802", "E741", "PT011", "PT009"]

[lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = ["tskit", "_tskit"]